all:
  vars:
    alb_dns: alb-f581648-1932363005.ap-southeast-1.elb.amazonaws.com
    mongodb_ip: 10.10.5.84
    key_file: >-
      /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
    bastion_host: 54.179.112.19
bastion:
  hosts:
    bastion1:
      ansible_host: 54.179.112.19
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
frontend:
  hosts:
    frontend1:
      ansible_host: 18.140.56.21
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
mongodb:
  hosts:
    mongo:
      ansible_host: 10.10.5.84
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
      ansible_ssh_common_args: >-
        -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o
        ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -i
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
        ubuntu@54.179.112.19"
