all:
  vars:
    alb_dns: alb-d073338-144677661.ap-southeast-1.elb.amazonaws.com
    mongodb_ip: 10.10.3.199
    key_file: >-
      /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
    bastion_host: 54.251.84.106
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q
      ubuntu@54.251.84.106 -i
      /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem"
bastion:
  hosts:
    bastion1:
      ansible_host: 54.251.84.106
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
frontend:
  hosts:
    frontend1:
      ansible_host: 13.228.79.29
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
backend:
  hosts:
    backend1:
      ansible_host: 10.10.3.249
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
    backend2:
      ansible_host: 10.10.3.116
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
mongodb:
  hosts:
    mongo:
      ansible_host: 10.10.3.199
      ansible_user: ubuntu
      ansible_ssh_private_key_file: >-
        /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
