all:
  vars:
    alb_dns: alb-552cb37-597925706.ap-southeast-1.elb.amazonaws.com
    mongodb_ip: 10.10.5.225
    key_file: /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
    bastion_host: 13.213.48.81
bastion:
  hosts:
    bastion1:
      ansible_host: 13.213.48.81
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
frontend:
  hosts:
    frontend1:
      ansible_host: 54.251.177.100
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
mongodb:
  hosts:
    mongo:
      ansible_host: 10.10.5.225
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -W %h:%p -o StrictHostKeyChecking=no -i /home/bayajidswe/My-files/poridhi-project/simply-done/pulumi_IaC/MyKeyPair.pem ubuntu@13.213.48.81\""
